"""add_cnis_calculo_rmi

Revision ID: 0dfdd7e72f58
Revises: d03d1960cbaa
Create Date: 2026-06-12 18:59:31.781300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfdd7e72f58'
down_revision: Union[str, None] = 'd03d1960cbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnis',
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cliente_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('nome_segurado', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nis', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('arquivo_original_nome', sa.String(length=255), nullable=True),
    sa.Column('arquivo_original_hash', sa.String(length=64), nullable=True),
    sa.Column('periodo_inicial_cn', sa.Date(), nullable=True),
    sa.Column('periodo_final_cn', sa.Date(), nullable=True),
    sa.Column('tempo_contribuicao_total_dias', sa.Integer(), nullable=True),
    sa.Column('tempo_contribuicao_anos', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_contribuicoes', sa.Integer(), nullable=True),
    sa.Column('maior_salario_contribuicao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('media_salarios_contribuicao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status_processamento', sa.Enum('pendente', 'processando', 'concluido', 'erro', name='cnis_status_enum'), nullable=False),
    sa.Column('erros_validacao', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cnis_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cnis_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('calculos_rmi',
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cnis_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cliente_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('calculado_por', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('nome_calculo', sa.String(length=100), nullable=False),
    sa.Column('tipo_beneficio', sa.Enum('aposentadoria_idade_urbana', 'aposentadoria_idade_rural', 'aposentadoria_tempo_contribuicao', 'aposentadoria_especial_15', 'aposentadoria_especial_20', 'aposentadoria_especial_25', 'aposentadoria_pcd_idade', 'aposentadoria_pcd_tempo', 'auxilio_doenca', 'aposentadoria_invalidez', 'salario_maternidade', 'pensao_morte', name='tipo_beneficio_enum'), nullable=False),
    sa.Column('regra_aplicada', sa.String(length=100), nullable=True),
    sa.Column('data_der', sa.Date(), nullable=False),
    sa.Column('idade_na_der', sa.Integer(), nullable=False),
    sa.Column('tempo_contribuicao_na_der', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('salario_beneficio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coeficiente_calculo', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('fator_previdenciario', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('fator_acumulador', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rmi_calculada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rmi_teto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rmi_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('detalhamento_calculo', sa.JSON(), nullable=False),
    sa.Column('requisitos_atendidos', sa.JSON(), nullable=True),
    sa.Column('rmi_regra_anterior', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferenca_reforma', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calculo_valido', sa.Boolean(), nullable=False),
    sa.Column('alertas', sa.JSON(), nullable=True),
    sa.Column('erros', sa.JSON(), nullable=True),
    sa.Column('versao_calculo', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calculado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculos_rmi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculos_rmi_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculos_rmi_cnis_id'), ['cnis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculos_rmi_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cnis_periodos_contribuicao',
    sa.Column('cnis_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cnpj_empregador', sa.String(length=14), nullable=True),
    sa.Column('razao_social_empregador', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('tipo_contribuinte', sa.Enum('empregado', 'empregador', 'contribuinte_individual', 'segurado_especial', 'facultativo', 'estagiario', 'avulso', 'dirigente_sindical', name='tipo_contribuinte_enum'), nullable=True),
    sa.Column('categoria', sa.String(length=10), nullable=True),
    sa.Column('dias_contribuidos', sa.Integer(), nullable=False),
    sa.Column('indicador_aposentadoria_especial', sa.Boolean(), nullable=False),
    sa.Column('agente_nocivo', sa.String(length=100), nullable=True),
    sa.Column('grau_deficiencia', sa.Enum('leve', 'moderada', 'grave', name='grau_deficiencia_enum'), nullable=True),
    sa.Column('total_remuneracoes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantidade_remuneracoes', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('periodo_valido', sa.Boolean(), nullable=False),
    sa.Column('motivo_invalidacao', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cnis_periodos_contribuicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cnis_periodos_contribuicao_cnis_id'), ['cnis_id'], unique=False)

    op.create_table('simulacoes_cenarios',
    sa.Column('cnis_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('nome_simulacao', sa.String(length=100), nullable=True),
    sa.Column('data_simulacao_futura', sa.Date(), nullable=False),
    sa.Column('taxa_crescimento_salario', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('taxa_inflacao_anual', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('idade_na_data', sa.Integer(), nullable=True),
    sa.Column('tempo_contribuicao_projetado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('salario_beneficio_projetado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rmi_projetada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rmi_valor_atual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulacoes_cenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulacoes_cenarios_cnis_id'), ['cnis_id'], unique=False)

    op.create_table('cnis_remuneracoes',
    sa.Column('cnis_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('periodo_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('salario_contribuicao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salario_contribuicao_corrigido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('teto_inss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_calculo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_remuneracao', sa.Enum('salario', '13o_salario', 'ferias', 'rescisao', 'adicional_noturno', 'hora_extra', 'comissao', 'gratificacao', 'outros', name='tipo_remuneracao_enum'), nullable=True),
    sa.Column('contribuiu_inss', sa.Boolean(), nullable=False),
    sa.Column('valor_contribuicao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_valido', sa.Boolean(), nullable=False),
    sa.Column('acima_teto', sa.Boolean(), nullable=False),
    sa.Column('abaixo_minimo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['cnis_periodos_contribuicao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cnis_remuneracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cnis_remuneracoes_cnis_id'), ['cnis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cnis_remuneracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cnis_remuneracoes_cnis_id'))

    op.drop_table('cnis_remuneracoes')
    with op.batch_alter_table('simulacoes_cenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulacoes_cenarios_cnis_id'))

    op.drop_table('simulacoes_cenarios')
    with op.batch_alter_table('cnis_periodos_contribuicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cnis_periodos_contribuicao_cnis_id'))

    op.drop_table('cnis_periodos_contribuicao')
    with op.batch_alter_table('calculos_rmi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculos_rmi_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_calculos_rmi_cnis_id'))
        batch_op.drop_index(batch_op.f('ix_calculos_rmi_cliente_id'))

    op.drop_table('calculos_rmi')
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cnis_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cnis_cliente_id'))

    op.drop_table('cnis')
    # ### end Alembic commands ###
