"""make_client_fields_nullable

Revision ID: 118ffbaaaf00
Revises: 0dfdd7e72f58
Create Date: 2026-06-12 19:10:43.738775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '118ffbaaaf00'
down_revision: Union[str, None] = '0dfdd7e72f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cnis_remuneracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cnis_remuneracoes_cnis_id'))

    op.drop_table('cnis_remuneracoes')
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cnis_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_cnis_tenant_id'))

    op.drop_table('cnis')
    with op.batch_alter_table('calculos_rmi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculos_rmi_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_calculos_rmi_cnis_id'))
        batch_op.drop_index(batch_op.f('ix_calculos_rmi_tenant_id'))

    op.drop_table('calculos_rmi')
    with op.batch_alter_table('cnis_periodos_contribuicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cnis_periodos_contribuicao_cnis_id'))

    op.drop_table('cnis_periodos_contribuicao')
    with op.batch_alter_table('simulacoes_cenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulacoes_cenarios_cnis_id'))

    op.drop_table('simulacoes_cenarios')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('rg',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('nome_mae',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nis',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('nis',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('nome_mae',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('rg',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    op.create_table('simulacoes_cenarios',
    sa.Column('cnis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('nome_simulacao', sa.VARCHAR(length=100), nullable=True),
    sa.Column('data_simulacao_futura', sa.DATE(), nullable=False),
    sa.Column('taxa_crescimento_salario', sa.NUMERIC(precision=5, scale=4), nullable=True),
    sa.Column('taxa_inflacao_anual', sa.NUMERIC(precision=5, scale=4), nullable=True),
    sa.Column('idade_na_data', sa.INTEGER(), nullable=True),
    sa.Column('tempo_contribuicao_projetado', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('salario_beneficio_projetado', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rmi_projetada', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rmi_valor_atual', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulacoes_cenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulacoes_cenarios_cnis_id'), ['cnis_id'], unique=False)

    op.create_table('cnis_periodos_contribuicao',
    sa.Column('cnis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('cnpj_empregador', sa.VARCHAR(length=14), nullable=True),
    sa.Column('razao_social_empregador', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('tipo_contribuinte', sa.VARCHAR(length=23), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dias_contribuidos', sa.INTEGER(), nullable=False),
    sa.Column('indicador_aposentadoria_especial', sa.BOOLEAN(), nullable=False),
    sa.Column('agente_nocivo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('grau_deficiencia', sa.VARCHAR(length=8), nullable=True),
    sa.Column('total_remuneracoes', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('quantidade_remuneracoes', sa.INTEGER(), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('periodo_valido', sa.BOOLEAN(), nullable=False),
    sa.Column('motivo_invalidacao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cnis_periodos_contribuicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cnis_periodos_contribuicao_cnis_id'), ['cnis_id'], unique=False)

    op.create_table('calculos_rmi',
    sa.Column('tenant_id', sa.CHAR(length=32), nullable=False),
    sa.Column('cnis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
    sa.Column('calculado_por', sa.CHAR(length=32), nullable=True),
    sa.Column('nome_calculo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_beneficio', sa.VARCHAR(length=32), nullable=False),
    sa.Column('regra_aplicada', sa.VARCHAR(length=100), nullable=True),
    sa.Column('data_der', sa.DATE(), nullable=False),
    sa.Column('idade_na_der', sa.INTEGER(), nullable=False),
    sa.Column('tempo_contribuicao_na_der', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('salario_beneficio', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('coeficiente_calculo', sa.NUMERIC(precision=5, scale=4), nullable=False),
    sa.Column('fator_previdenciario', sa.NUMERIC(precision=10, scale=6), nullable=True),
    sa.Column('fator_acumulador', sa.NUMERIC(precision=5, scale=4), nullable=True),
    sa.Column('rmi_calculada', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('rmi_teto', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rmi_final', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('detalhamento_calculo', sqlite.JSON(), nullable=False),
    sa.Column('requisitos_atendidos', sqlite.JSON(), nullable=True),
    sa.Column('rmi_regra_anterior', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('diferenca_reforma', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('calculo_valido', sa.BOOLEAN(), nullable=False),
    sa.Column('alertas', sqlite.JSON(), nullable=True),
    sa.Column('erros', sqlite.JSON(), nullable=True),
    sa.Column('versao_calculo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calculado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculos_rmi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculos_rmi_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculos_rmi_cnis_id'), ['cnis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculos_rmi_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('cnis',
    sa.Column('tenant_id', sa.CHAR(length=32), nullable=False),
    sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
    sa.Column('nome_segurado', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), nullable=False),
    sa.Column('nis', sa.VARCHAR(length=11), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('arquivo_original_nome', sa.VARCHAR(length=255), nullable=True),
    sa.Column('arquivo_original_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('periodo_inicial_cn', sa.DATE(), nullable=True),
    sa.Column('periodo_final_cn', sa.DATE(), nullable=True),
    sa.Column('tempo_contribuicao_total_dias', sa.INTEGER(), nullable=True),
    sa.Column('tempo_contribuicao_anos', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('total_contribuicoes', sa.INTEGER(), nullable=True),
    sa.Column('maior_salario_contribuicao', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('media_salarios_contribuicao', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('status_processamento', sa.VARCHAR(length=11), nullable=False),
    sa.Column('erros_validacao', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cnis_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cnis_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('cnis_remuneracoes',
    sa.Column('cnis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('periodo_id', sa.CHAR(length=32), nullable=True),
    sa.Column('mes_referencia', sa.DATE(), nullable=False),
    sa.Column('ano', sa.INTEGER(), nullable=False),
    sa.Column('mes', sa.INTEGER(), nullable=False),
    sa.Column('salario_contribuicao', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('salario_contribuicao_corrigido', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('teto_inss', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('base_calculo', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('tipo_remuneracao', sa.VARCHAR(length=17), nullable=True),
    sa.Column('contribuiu_inss', sa.BOOLEAN(), nullable=False),
    sa.Column('valor_contribuicao', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('salario_valido', sa.BOOLEAN(), nullable=False),
    sa.Column('acima_teto', sa.BOOLEAN(), nullable=False),
    sa.Column('abaixo_minimo', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cnis_id'], ['cnis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['cnis_periodos_contribuicao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cnis_remuneracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cnis_remuneracoes_cnis_id'), ['cnis_id'], unique=False)

    # ### end Alembic commands ###
