"""add_media_corrigida_cnis

Revision ID: 1ed66a2ddd84
Revises: a1b2c3d4e5f6
Create Date: 2026-06-14 13:58:27.708031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed66a2ddd84'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_salarios_contribuicao_corrigida', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.drop_column('media_salarios_contribuicao_corrigida')

    # ### end Alembic commands ###
