"""make_cnis_nis_nullable

Revision ID: 2c019606db1a
Revises: 1ed66a2ddd84
Create Date: 2026-06-14 14:35:18.759314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c019606db1a'
down_revision: Union[str, None] = '1ed66a2ddd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.alter_column('nis',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cnis', schema=None) as batch_op:
        batch_op.alter_column('nis',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
