"""add_processos_prazos_alertas

Revision ID: 76aae24ae305
Revises: c91f20865d2c
Create Date: 2026-06-12 23:11:23.342639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76aae24ae305'
down_revision: Union[str, None] = 'c91f20865d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos_judiciais',
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cliente_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('numero_cnj', sa.String(length=25), nullable=False),
    sa.Column('tribunal', sa.Enum('TRF1', 'TRF3', 'TRF4', 'TNU', 'STJ', name='tribunal_enum'), nullable=False),
    sa.Column('vara', sa.String(length=200), nullable=True),
    sa.Column('comarca', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('classe_processual', sa.String(length=150), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'suspenso', 'arquivado', 'encerrado', name='status_processo_enum'), nullable=False),
    sa.Column('monitoramento_ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero_cnj', name='uq_processo_tenant_cnj')
    )
    with op.batch_alter_table('processos_judiciais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_judiciais_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_judiciais_numero_cnj'), ['numero_cnj'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_judiciais_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('movimentacoes_processuais',
    sa.Column('processo_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('INTIMACAO', 'SENTENCA', 'DESPACHO', 'ACORDAO', 'RECURSO', 'PETICAO', 'OUTROS', name='tipo_movimentacao_enum'), nullable=False),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=False),
    sa.Column('origem_tribunal', sa.String(length=10), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_judiciais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processo_id', 'hash_conteudo', name='uq_movimentacao_hash')
    )
    with op.batch_alter_table('movimentacoes_processuais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_processuais_data_movimentacao'), ['data_movimentacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_processuais_processo_id'), ['processo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_processuais_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alertas_processuais',
    sa.Column('processo_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('movimentacao_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tipo', sa.Enum('NOVA_MOVIMENTACAO', 'PRAZO_VENCENDO', 'PRAZO_VENCIDO', 'SENTENCA', 'INTIMACAO', name='tipo_alerta_enum'), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lido', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_processuais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_judiciais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas_processuais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_processuais_lido'), ['lido'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_processuais_processo_id'), ['processo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_processuais_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('prazos_processuais',
    sa.Column('processo_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('movimentacao_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tipo_prazo', sa.Enum('CONTESTACAO', 'RECURSO', 'CONTRARRAZOES', 'MANIFESTACAO', 'CUMPRIMENTO_SENTENCA', 'OUTROS', name='tipo_prazo_enum'), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('dias_corridos', sa.Integer(), nullable=False),
    sa.Column('dias_uteis', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_processuais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_judiciais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prazos_processuais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prazos_processuais_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_prazos_processuais_processo_id'), ['processo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prazos_processuais_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prazos_processuais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prazos_processuais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_prazos_processuais_processo_id'))
        batch_op.drop_index(batch_op.f('ix_prazos_processuais_data_vencimento'))

    op.drop_table('prazos_processuais')
    with op.batch_alter_table('alertas_processuais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_processuais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alertas_processuais_processo_id'))
        batch_op.drop_index(batch_op.f('ix_alertas_processuais_lido'))

    op.drop_table('alertas_processuais')
    with op.batch_alter_table('movimentacoes_processuais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_processuais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_processuais_processo_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_processuais_data_movimentacao'))

    op.drop_table('movimentacoes_processuais')
    with op.batch_alter_table('processos_judiciais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_judiciais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_processos_judiciais_numero_cnj'))
        batch_op.drop_index(batch_op.f('ix_processos_judiciais_cliente_id'))

    op.drop_table('processos_judiciais')
    # ### end Alembic commands ###
