"""initial_uuid_fix

Revision ID: d03d1960cbaa
Revises: 
Create Date: 2026-06-12 18:51:35.786513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03d1960cbaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('clients',
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('rg_orgao_expedidor', sa.String(length=10), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nome_mae', sa.String(length=255), nullable=False),
    sa.Column('nome_pai', sa.String(length=255), nullable=True),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'divorciado', 'viuvo', 'uniao_estavel', name='estado_civil_enum'), nullable=True),
    sa.Column('genero', sa.Enum('masculino', 'feminino', 'outro', name='genero_enum'), nullable=True),
    sa.Column('nis', sa.String(length=11), nullable=False),
    sa.Column('ctps_numero', sa.String(length=10), nullable=True),
    sa.Column('ctps_serie', sa.String(length=5), nullable=True),
    sa.Column('escolaridade', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone_celular', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=False),
    sa.Column('telefone_fixo', sa.String(length=20), nullable=True),
    sa.Column('contato_emergencia_nome', sa.String(length=255), nullable=True),
    sa.Column('contato_emergencia_telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo_residencia', sa.String(length=20), nullable=True),
    sa.Column('renda_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('possui_deficiencia', sa.Boolean(), nullable=False),
    sa.Column('tipo_deficiencia', sa.String(length=100), nullable=True),
    sa.Column('tempo_contribuicao_anos', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cpf', name='uq_client_tenant_cpf'),
    sa.UniqueConstraint('tenant_id', 'nis', name='uq_client_tenant_nis')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dependentes',
    sa.Column('cliente_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('parentesco', sa.Enum('filho', 'conjuge', 'companheiro', 'outros', name='parentesco_enum'), nullable=True),
    sa.Column('e_beneficiario', sa.Boolean(), nullable=False),
    sa.Column('percentual_dependencia', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependentes_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependentes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependentes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_dependentes_cliente_id'))

    op.drop_table('dependentes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))

    op.drop_table('clients')
    op.drop_table('tenants')
    # ### end Alembic commands ###
