"""add_salario_minimo

Revision ID: fa3cc47a11e4
Revises: 76aae24ae305
Create Date: 2026-06-14 13:24:29.069939

"""
import uuid
from datetime import date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Histórico completo do salário mínimo brasileiro (pós-Plano Real)
# Fonte: legislação federal — cada entrada representa o início da vigência.
# Para adicionar novos valores: inserir nova linha com a data de vigência.
_HISTORICO = [
    (date(1994,  9,  1), "64.79"),
    (date(1995,  5,  1), "100.00"),
    (date(1996,  5,  1), "112.00"),
    (date(1997,  5,  1), "120.00"),
    (date(1998,  5,  1), "130.00"),
    (date(1999,  4,  1), "136.00"),
    (date(2000,  4,  3), "151.00"),
    (date(2001,  4,  1), "180.00"),
    (date(2002,  4,  1), "200.00"),
    (date(2003,  4,  1), "240.00"),
    (date(2004,  5,  1), "260.00"),
    (date(2005,  5,  1), "300.00"),
    (date(2006,  4,  1), "350.00"),
    (date(2007,  4,  1), "380.00"),
    (date(2008,  3,  1), "415.00"),
    (date(2009,  2,  1), "465.00"),
    (date(2010,  1,  1), "510.00"),
    (date(2011,  1,  1), "545.00"),
    (date(2012,  1,  1), "622.00"),
    (date(2013,  1,  1), "678.00"),
    (date(2014,  1,  1), "724.00"),
    (date(2015,  1,  1), "788.00"),
    (date(2016,  1,  1), "880.00"),
    (date(2017,  1,  1), "937.00"),
    (date(2018,  1,  1), "954.00"),
    (date(2019,  1,  1), "998.00"),
    (date(2020,  2,  1), "1045.00"),
    (date(2021,  1,  1), "1100.00"),
    (date(2022,  1,  1), "1212.00"),
    (date(2023,  1,  1), "1320.00"),
    (date(2024,  1,  1), "1412.00"),
    (date(2025,  1,  1), "1518.00"),
]


# revision identifiers, used by Alembic.
revision: str = 'fa3cc47a11e4'
down_revision: Union[str, None] = '76aae24ae305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salario_minimo',
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vigencia_inicio')
    )
    with op.batch_alter_table('salario_minimo', schema=None) as batch_op:
        batch_op.create_index('ix_salario_minimo_vigencia', ['vigencia_inicio'], unique=False)

    # Popula com histórico completo
    sm_table = sa.table(
        "salario_minimo",
        sa.column("id", sa.String),
        sa.column("vigencia_inicio", sa.Date),
        sa.column("valor", sa.Numeric),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    from datetime import datetime
    now = datetime.utcnow()
    op.bulk_insert(sm_table, [
        {"id": str(uuid.uuid4()), "vigencia_inicio": vi, "valor": v,
         "created_at": now, "updated_at": now}
        for vi, v in _HISTORICO
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salario_minimo', schema=None) as batch_op:
        batch_op.drop_index('ix_salario_minimo_vigencia')

    op.drop_table('salario_minimo')
    # ### end Alembic commands ###
